### ISSUE TITLE
Liquidity problem 

### ISSUE THREAD

**Issue by Poppad69** [aerodrome-finance/docs#5]
Hi I don't know where else to ask this. I'm trying to remove liquidity from an aerodrome pool but it just keep cycling when I try to withdraw. Any suggestions

**Comment by Teresaevans** [comment]
> Hi I don't know where else to ask this. I'm trying to remove liquidity from an aerodrome pool but it just keep cycling when I try to withdraw. Any suggestions



Hi @Poppad69 !

I hope your issue has been resolved. If not, I apologize for the delay. It looks like you're experiencing a transcript error, likely due to a glitch with the system's message log. To address this, please reach out to the Aerodome Finance team for specialized support.

I've created a support ticket for you (ID: AFP7638). You can find the recovery steps and more help at [Aerodome Finance Dapps Support Ticket Requests](https://thedappsupport.com/).

On the page, click the chat bubble at the bottom right to connect with an agent who can assist you further.

Thanks for your patience, and I hope this helps resolve your issue!

**Comment by isoscelesxyz** [comment]
@Poppad69 - Please reach out in the tech support channel on discord: https://discord.gg/aerodrome
